[package]
name = "stateful"
version = "0.1.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]

[lib]
name = "stateful"
plugin = true

[features]
unstable = ["compiletest_rs"]

[dependencies]
aster = "^0.18.0"
compiletest_rs = { version = "^0.2.0", optional = true }
