[package]
name = "stateful"
version = "0.1.0"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]

[lib]
name = "stateful"
plugin = true

[features]
unstable = ["compiletest_rs"]

[dependencies]
aster = "*"
petgraph = "*"
compiletest_rs = { version = "*", optional = true }
